# Site settings
title: AIDA MUBA
email: s.aid@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:
artstation_username:  aidamuba
instagram_username:  aida_muba

# Build settings
markdown: kramdown
permalink: pretty

imagesurl: "/assets/images/"
thumbsurl: "/assets/thumbnails/"
